Warehouse/Warehouse/Models/Delivery.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Warehouse.Models
{
    public class Delivery
    {
        [Key]
        [DisplayName("Azonosító")]
        public int Id { get; set; }

        [Range(0, int.MaxValue, ErrorMessage = "Nem lehet negatív.")]
        [DisplayName("Termék azonosító")]
        public int ItemId { get; set; }

        [Range(0, int.MaxValue, ErrorMessage = "Nem lehet negatív.")]
        [DisplayName("Darabszám")]
        public int Quantity { get; set; }

        [Range(0, int.MaxValue, ErrorMessage = "Nem lehet negatív.")]
        [DisplayName("Forrás azonosító")]
        public int FromAddressId { get; set; }

        [Range(0, int.MaxValue, ErrorMessage = "Nem lehet negatív.")]
        [DisplayName("Cél azonosító")]
        public int ToAddressId { get; set; }

        [DisplayName("Szállítás kezdete")]
        public DateTime Start { get; set; }

        [DisplayName("Megérkezett")]
        public bool HasArrived { get; set; }

        [DisplayName("Megjegyzés")]
        public string Comment { get; set; }
    }
}

Warehouse/Warehouse/Controllers/DeliveryController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Warehouse.Data;
using Warehouse.Models;

namespace Warehouse.Controllers
{
    public class DeliveryController : Controller
    {
        private readonly ApplicationDbContext _db;

        public DeliveryController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            IEnumerable<Delivery> objList = _db.Deliveries;
            return View(objList);
        }

        //get
        public IActionResult Create()
        {
            return View();
        }

        //post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Delivery obj)
        {
            if (ModelState.IsValid)
            {
                _db.Deliveries.Add(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        //get delete
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var obj = _db.Deliveries.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            return View(obj);
        }


        //post delete
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? id)
        {
            var obj = _db.Deliveries.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            _db.Deliveries.Remove(obj);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }        
    }
}

Warehouse/Warehouse/Views/Delivery/Create.cshtml
@model Warehouse.Models.Delivery

<form method="post" asp-action="Create">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="border p-3">
        <div class="form-group row">
            <h2 class="text-black-50 pl-3">Szállítás létrehozása</h2>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="form-group row">
                    <div class="col-3 text-right">
                        <label asp-for="ItemId"></label>
                    </div>
                    <div class="dropdown ml-2 mt-0">
                        <button class="btn dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Azonosító
                        </button>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                            <a class="dropdown-item" href="#">1</a>
                            <a class="dropdown-item" href="#">2</a>
                            <a class="dropdown-item" href="#">3</a>
                        </div>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-3 text-right">
                        <label asp-for="Quantity"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Quantity" class="form-control" />
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-3 text-right">
                        <label asp-for="FromAddressId"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="FromAddressId" class="form-control" />
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-3 text-right">
                        <label asp-for="ToAddressId"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="ToAddressId" class="form-control" />
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-3 text-right">
                        <label asp-for="Start"></label>
                    </div>
                    <div class="col-8">
                        <input type="datetime-local" asp-for="Start" class="form-control" />
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-3 text-right">
                        <label asp-for="HasArrived"></label>
                    </div>
                    <div class="col-8 ml-3">
                        <input type="checkbox" asp-for="HasArrived" class="form-check-input" />
                    </div>
                </div>


                <div class="form-group row">
                    <div class="col-3 text-right">
                        <label asp-for="Comment"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Comment" class="form-control" />
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-9 offset-2 row">
                        <div class="col">
                            <a asp-action="Index" class="btn btn-danger w-75">Vissza</a>
                        </div>
                        <div class="col">
                            <input type="submit" class="btn btn-success w-75" value="Mentés" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

Warehouse/Warehouse/Views/Delivery/Delete.cshtml
@model Warehouse.Models.Delivery

<form method="post" asp-action="Delte">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="border p-3">
        <div class="form-group row">
            <h2 class="text-black-50 pl-3">Szállítás alatt lévő termék adatainak módosítása</h2>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="form-group row">
                    <div class="col-3 text-right">
                        <label asp-for="ItemId"></label>
                    </div>
                    <div class="dropdown ml-2 mt-0">
                        <button class="btn dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Azonosító
                        </button>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                            <a class="dropdown-item" href="#">1</a>
                            <a class="dropdown-item" href="#">2</a>
                            <a class="dropdown-item" href="#">3</a>
                        </div>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-3 text-right">
                        <label asp-for="Quantity"></label>
                    </div>
                    <div class="col-8">
                        <input readonly asp-for="Quantity" class="form-control" />
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-3 text-right">
                        <label asp-for="FromAddressId"></label>
                    </div>
                    <div class="col-8">
                        <input readonly asp-for="FromAddressId" class="form-control" />
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-3 text-right">
                        <label asp-for="ToAddressId"></label>
                    </div>
                    <div class="col-8">
                        <input readonly asp-for="ToAddressId" class="form-control" />
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-3 text-right">
                        <label asp-for="Start"></label>
                    </div>
                    <div class="col-8">
                        <input readonly type="datetime-local" asp-for="Start" class="form-control" />
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-3 text-right">
                        <label asp-for="HasArrived"></label>
                    </div>
                    <div class="col-8 ml-3">
                        <input readonly type="checkbox" asp-for="HasArrived" class="form-check-input" />
                    </div>
                </div>


                <div class="form-group row">
                    <div class="col-3 text-right">
                        <label asp-for="Comment"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Comment" class="form-control" />
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-9 offset-2 row">
                        <div class="col">
                            <a asp-action="Index" class="btn btn-danger w-75">Vissza</a>
                        </div>
                        <div class="col">
                            <input type="submit" class="btn btn-success w-75" value="Mentés" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

Warehouse/Warehouse/Views/Delivery/Index.cshtml
@model IEnumerable<Warehouse.Models.Delivery>

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Szállítás alatt lévő termékek listája</h2>
        </div>
        <div class="col-6 text-right">
            <a class="btn btn-primary" asp-controller="Delivery" asp-action="Create" data-toggle="tooltip" data-placement="bottom" title="Új szállítás hozzáadása">Új szállítás</a>
        </div>
    </div>

    <div class="d-flex form-group w-25 justify-content-center align-items-center">
        <input type="text" class="form-control" placeholder="Keresés...">
    </div>


    @if (Model.Count() > 0)
    {
        <div class="container" style="margin-top:35px">
            <table id="mytable" class="table table-bordered table-hover" style="width:100%">
                <thead class="thead">
                    <tr class="justify-content-center align-items-center">
                        <th>
                            Azonosító
                        </th>
                        <th>
                            Mennyiség
                        </th>
                        <th>
                            Kiindulás
                        </th>
                        <th>
                            Cél
                        </th>
                        <th>
                            Szállítás kezdete
                        </th>
                        <th>
                            Megjegyzés
                        </th>
                        <th>
                            Műveletek
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {                       
                    <tr>
                        <td width="15%">@item.ItemId</td>
                        <td width="15%">@item.Quantity</td>
                        <td width="10%">@item.FromAddressId</td>
                        <td width="10%">@item.ToAddressId</td>
                        <td width="30%">@item.Start</td>
                        <td width="30%">@item.Comment</td>
                        <td width="16%">
                            <div>
                                <a class="btn btn-success ml-3" asp-controller="Delivery" asp-action="Delete" asp-route-Id="@item.Id" data-toggle="tooltip" data-placement="bottom" title="Megérkezett"><i class="fas fa-check"></i></a>
                            </div>
                        </td>
                    </tr>                      
                    }
                </tbody>
            </table>
            <div class="flex-row">
                <h5>Sorok száma egy oldalon</h5>
                <div class="form-group">
                    <select name="state" id="maxRows" class="form-control" style="width:150px;">
                        <option value="10">10</option>
                        <option value="25">25</option>
                        <option value="50">50</option>
                        <option value="100">100</option>
                    </select>
                </div>
                <div class="pagination-container">
                    <nav>
                        <ul class="pagination"></ul>
                    </nav>
                </div>
            </div>

            <nav aria-label="Page navigation example" class="d-flex flex-row-reverse">
                <ul class="pagination">
                    <li class="page-item">
                        <a class="page-link" href="#" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                            <span class="sr-only">Previous</span>
                        </a>
                    </li>
                    <li class="page-item"><a class="page-link" href="#">1</a></li>
                    <li class="page-item"><a class="page-link" href="#">2</a></li>
                    <li class="page-item"><a class="page-link" href="#">3</a></li>
                    <li class="page-item">
                        <a class="page-link" href="#" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                            <span class="sr-only">Next</span>
                        </a>
                    </li>
                </ul>
            </nav>
        </div>
    }
    else
    {
        <p>Nincs megjeleníthető termék.</p>
    }
</div>